// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission5_ear69.Models;

namespace Mission5_ear69.Migrations
{
    [DbContext(typeof(MoiveAppContext))]
    partial class MoiveAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Mission5_ear69.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            Director = "Seth Rogen/EvenGoldberg",
                            Edit = false,
                            Lent = "no",
                            Notes = "Funny film",
                            Rating = "R",
                            Title = "This is the End",
                            Year = 2013
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Drama",
                            Director = "Robert Eggers",
                            Edit = false,
                            Lent = "no",
                            Notes = "Willem Dafoe is the best actor",
                            Rating = "R",
                            Title = "LightHouse",
                            Year = 2019
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Drama",
                            Director = "Daniel Brothers",
                            Edit = false,
                            Lent = "no",
                            Notes = "The best movie ever made",
                            Rating = "R",
                            Title = "Everything Everywhere All At Once",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
